### ISSUE TITLE
Bug fixes and adding special characters [bug, enhancement]

### ISSUE THREAD

**Issue by ghost** [Busybasket/Wordlist-Creator#3]
I noticed that this variable is only defined but not used anywhere` txt = 0`
I think it would be useful to add special characters to the `values` list so that we can create a more comprehensive wordlist.
Finally, I believe that if a user manual is written in the README.md, it will provide ease of use.

**Comment by eminnates** [comment]
> I noticed that this variable is only defined but not used anywhere` txt = 0`
> I think it would be useful to add special characters to the `values` list so that we can create a more comprehensive wordlist.
> Finally, I believe that if a user manual is written in the README.md, it will provide ease of use.

Thanks 04L you are a real life hero

**Comment by Busybasket** [comment]
> > I noticed that this variable is only defined but not used anywhere` txt = 0`
> > I think it would be useful to add special characters to the `values` list so that we can create a more comprehensive wordlist.
> > Finally, I believe that if a user manual is written in the README.md, it will provide ease of use.
> 
> Thanks 04L you are a real life hero
